version: '3.9'

services:
  db:
    image: mysql:latest
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      TZ: 'Asia/Tokyo'
    restart: unless-stopped
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8080:80
    volumes:
      - ./phpmyadmin_data:/var/lib/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: $PMA_USER
      PMA_PASSWORD: $PMA_PASSWORD
    restart: unless-stopped
    depends_on:
      - db

  gunicorn:
    build: .
    image: gunicorn:docker-nkc2023gr11-mysql-nginx-gunicorn-compose
    env_file: .env
    volumes:
      - .:/usr/src/app/
      - gunicorn:/var/run/gunicorn
    restart: unless-stopped
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - gunicorn:/var/run/gunicorn
    restart: unless-stopped
    depends_on:
      - gunicorn

volumes:
  gunicorn:
    driver: local
  mysql_data:
  phpmyadmin_data: