version: '3.7'

services:
  gunicorn:
    image: gunicorn:docker-nkc2023gr11-mysql-nginx-gunicorn-compose
    container_name: gunicorn_docker-nkc2023gr11-mysql-nginx-gunicorn-compose
    volumes:
      - .:/usr/src/app/
      - gunicorn:/var/run/gunicorn
    depends_on:
      - db

  db:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: docker_django_mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    volumes:
      - phpmyadmin_data:/var/lib/phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=admin
    depends_on:
      - db

  nginx:
    image: nginx:1.17.7
    container_name: nginx_docker-nkc2023gr11-mysql-nginx-gunicorn-compose
    depends_on:
      - gunicorn
    ports:
      - "80:80"
    volumes:
      - ./gunicorn.conf:/etc/nginx/conf.d/default.conf
      - gunicorn:/var/run/gunicorn

volumes:
  gunicorn:
    driver: local
  mysql_data:
  phpmyadmin_data: