# Generated by Django 4.1.2 on 2022-10-28 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DB',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Question', models.CharField(max_length=100)),
                ('Answer', models.CharField(blank=True, max_length=500, null=True)),
                ('Memo', models.CharField(blank=True, max_length=100, null=True)),
                ('FB', models.CharField(blank=True, max_length=100, null=True)),
                ('Contributor', models.CharField(blank=True, max_length=100, null=True)),
                ('WhoAnswers', models.CharField(blank=True, max_length=100, null=True)),
                ('FBer', models.CharField(blank=True, max_length=100, null=True)),
                ('Genre', models.CharField(blank=True, max_length=100, null=True)),
                ('AnswerReq', models.CharField(blank=True, max_length=100, null=True)),
                ('FBReq', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('account_image', models.ImageField(blank=True, upload_to='account_image')),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
